### ISSUE TITLE
Prettier 3.0 support

### ISSUE THREAD

**Issue by WayneEllery** [avocadowastaken/prettier-plugin-prisma#78]
**Describe the bug**
Prettier 3.0 has been released: https://prettier.io/blog/2023/07/05/3.0.0.html. It looks like that this plugin is no longer working with the new 3.0 version:
```
Checking formatting...
prisma/schema.prisma
[error] No parser could be inferred for file "/prisma/schema.prisma".
```

**To Reproduce**

1. Upgrade to Prettier 3.0
2. Install plugin
3. Perform check

**Expected behavior**
No error and schema is formatted

**Comment by avocadowastaken** [comment]
@WayneEllery hey! did you try to add `prettier-plugin-prisma` to the `plugins`?  Might be a problem with auto detection. See: https://prettier.io/docs/en/plugins.html#using-plugins

**Comment by WayneEllery** [comment]
Thanks. That worked
